const $ = (id) => document.getElementById(id);
let employees=[], entries=[], openEntries=[], loggedEmployee=null;
let settings={first_coffee_minutes:15,second_coffee_minutes:15,lunch_minutes:30,overtime_after_hours_day:8};

async function sha256(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function checkPin(emp,pin){if(emp.pin_hash){return await sha256(pin)===emp.pin_hash} return String(emp.pin_code||"")===String(pin)}
function toast(m){$("toast").textContent=m;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2300)}
function minsText(m){m=Number(m||0);return `${Math.floor(m/60)} klst ${String(m%60).padStart(2,"0")} mín`}
function fmtDate(v){if(!v)return"";return new Date(v).toLocaleString("is-IS",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function csvEscape(v){return `"${String(v??"").replaceAll('"','""')}"`}
function localISO(d,t){return new Date(`${d}T${t}:00`).toISOString()}
function skippedBreakMinutes(fc,sc,lu){return(!fc?Number(settings.first_coffee_minutes||0):0)+(!sc?Number(settings.second_coffee_minutes||0):0)+(!lu?Number(settings.lunch_minutes||0):0)}

async function init(){ $("monthPicker").value=new Date().toISOString().slice(0,7); bind(); await loadSettings(); await loadEmployees(); await loadEntries(); await loadOpenEntries();}
function bind(){
$("adminToggle").onclick=()=>$("adminSection").classList.toggle("hidden");$("adminLoginBtn").onclick=adminLogin;$("adminLogoutBtn").onclick=adminLogout;
$("employeeLoginBtn").onclick=employeeLogin;$("employeeLogoutBtn").onclick=employeeLogout;$("clockInBtn").onclick=clockIn;$("clockOutShowBtn").onclick=showClockOut;$("clockOutBtn").onclick=clockOut;
$("firstCoffee").onchange=previewPaid;$("secondCoffee").onchange=previewPaid;$("lunch").onchange=previewPaid;$("showChangePinBtn").onclick=()=>showChangePin(false);$("changePinBtn").onclick=changeMyPin;
$("addEmployeeBtn").onclick=addEmployee;$("addManualBtn").onclick=addManualEntry;$("saveSettingsBtn").onclick=saveSettings;$("exportCsvBtn").onclick=downloadCSV;$("copyPayrollBtn").onclick=copyPayroll;$("backupBtn").onclick=backup;$("monthPicker").onchange=loadEntries;
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>setTab(b.dataset.tab,b));
}
async function loadSettings(){const{data}=await db.from("app_settings").select("*");(data||[]).forEach(r=>settings[r.key]=Number(r.value));$("settingFirstCoffee").value=settings.first_coffee_minutes;$("settingSecondCoffee").value=settings.second_coffee_minutes;$("settingLunch").value=settings.lunch_minutes;$("settingOvertime").value=settings.overtime_after_hours_day;document.querySelectorAll("[data-setting]").forEach(e=>e.textContent=settings[e.dataset.setting])}
async function loadEmployees(){const{data,error}=await db.from("employees").select("*").order("name");if(error){console.error(error);return toast("Villa við starfsmenn")}employees=(data||[]).filter(e=>e.active!==false);const opts=employees.map(e=>`<option value="${e.id}">${e.name}</option>`).join("");$("employeeSelect").innerHTML=opts;$("manualEmployee").innerHTML=opts;$("employeesList").innerHTML=employees.map(e=>`<div class="empCard"><div><b>${e.name}</b><br><span class="muted small">Kennitala: ${e.national_id||"-"} · Starfsnr: ${e.employee_no||"-"} · PIN: ${e.pin_hash?"öruggt":(e.pin_code?"tímabundið":"vantar")} · Tímakaup: ${Number(e.hourly_rate||0).toLocaleString("is-IS")} kr</span></div><div class="row"><button class="secondary smallBtn" onclick="editEmployee('${e.id}')">Breyta</button><button class="secondary smallBtn" onclick="resetEmployeePin('${e.id}')">Endurstilla PIN</button><button class="red smallBtn" onclick="hideEmployee('${e.id}')">Eyða</button></div></div>`).join("")}
async function loadEntries(){const month=$("monthPicker").value||new Date().toISOString().slice(0,7);$("monthPicker").value=month;const start=new Date(`${month}-01T00:00:00`);const end=new Date(start);end.setMonth(end.getMonth()+1);const{data,error}=await db.from("time_entries").select("*").gte("clock_in",start.toISOString()).lt("clock_in",end.toISOString()).order("clock_in",{ascending:false});if(error){console.error(error);return toast("Villa við tímaskráningar")}entries=data||[];renderEntries();renderSummary();renderDashboard();renderMyEntries()}
async function loadOpenEntries(){const{data}=await db.from("time_entries").select("*").is("clock_out",null).not("clock_in","is",null).order("clock_in",{ascending:false});openEntries=data||[];renderOpenEntries();renderDashboard()}
function renderOpenEntries(){$("openEntriesBox").innerHTML=openEntries.length?openEntries.map(e=>`<span class="pill ok">🟢 ${e.employee_name} · ${fmtDate(e.clock_in)}</span>`).join(""):`<span class="pill">Enginn skráður inni núna</span>`}
function renderDashboard(){const today=new Date().toISOString().slice(0,10);const t=entries.filter(e=>e.clock_in&&new Date(e.clock_in).toISOString().slice(0,10)===today);const paid=t.reduce((a,e)=>a+Number(e.paid_minutes??e.total_minutes??0),0);const skipped=t.reduce((a,e)=>a+Number(e.skipped_break_minutes||0),0);$("dashboardStats").innerHTML=`<div class="stat"><span class="muted">Í vinnu núna</span><b>${openEntries.length}</b></div><div class="stat"><span class="muted">Skráðir í dag</span><b>${t.length}</b></div><div class="stat"><span class="muted">Greitt í dag</span><b>${minsText(paid)}</b></div><div class="stat"><span class="muted">Sleppt hlé</span><b>${minsText(skipped)}</b></div>`}
function renderEntries(){$("entriesBody").innerHTML=entries.map(e=>{const skipped=[e.first_coffee===false?"Fyrra kaffi sleppt":"",e.second_coffee===false?"Seinna kaffi sleppt":"",e.lunch===false?"Matur sleppt":"",e.absence_type||""].filter(Boolean).join(", ");const taken=[e.first_coffee?"Fyrra kaffi tekið":"",e.second_coffee?"Seinna kaffi tekið":"",e.lunch?"Matur tekinn":""].filter(Boolean).join(", ");return`<tr><td>${e.employee_name||""}</td><td>${fmtDate(e.clock_in)}</td><td>${fmtDate(e.clock_out)}</td><td>${taken||"-"}<br><span class="${skipped?"pill warn":"muted small"}">${skipped||"Engu sleppt"}</span></td><td>${minsText(e.total_minutes)}</td><td><b>${minsText(e.paid_minutes??e.total_minutes)}</b><br><span class="muted small">+${minsText(e.skipped_break_minutes||0)}</span></td><td>${e.note||""}</td><td><button class="red smallBtn" onclick="deleteEntry('${e.id}')">Eyða</button></td></tr>`}).join("")}
function renderSummary(){const s={};entries.forEach(e=>{const n=e.employee_name||"Óþekkt";if(!s[n])s[n]={real:0,paid:0,skipped:0,overtime:0,abs:0,days:new Set(),sf:0,ss:0,sl:0};const real=Number(e.total_minutes||0),paid=Number(e.paid_minutes??e.total_minutes??0);s[n].real+=real;s[n].paid+=paid;s[n].skipped+=Number(e.skipped_break_minutes||0);if(e.first_coffee===false)s[n].sf++;if(e.second_coffee===false)s[n].ss++;if(e.lunch===false)s[n].sl++;if(e.absence_type)s[n].abs++;if(e.clock_in)s[n].days.add(new Date(e.clock_in).toISOString().slice(0,10));const ot=Number(settings.overtime_after_hours_day||8)*60;if(paid>ot)s[n].overtime+=paid-ot});const rows=Object.entries(s).sort().map(([n,x])=>{const emp=employees.find(e=>e.name===n)||{};const wage=Math.round((Number(emp.hourly_rate||0)*x.paid)/60);return`<tr><td>${n}</td><td>${x.days.size}</td><td>${minsText(x.real)}</td><td><b>${minsText(x.paid)}</b></td><td>${minsText(x.skipped)}</td><td>${minsText(x.overtime)}</td><td><b>${wage.toLocaleString("is-IS")} kr</b></td><td>${x.sf}/${x.ss}/${x.sl}</td><td>${x.abs}</td></tr>`}).join("");$("summary").innerHTML=`<div class="tablewrap"><table><thead><tr><th>Starfsmaður</th><th>Dagar</th><th>Rauntími</th><th>Greiddur tími</th><th>Sleppt hlé</th><th>Yfirvinna</th><th>Áætluð laun</th><th>Sleppt F/S/M</th><th>Fjarvistir</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderMyEntries(){if(!loggedEmployee){$("myEntries").innerHTML="";return}const mine=entries.filter(e=>e.employee_id===loggedEmployee.id||e.employee_name===loggedEmployee.name).slice(0,8);$("myEntries").innerHTML=mine.length?mine.map(e=>`<span class="pill">${fmtDate(e.clock_in)} · ${minsText(e.paid_minutes??e.total_minutes)}</span>`).join(""):`<span class="pill">Engar skráningar í þessum mánuði</span>`}

async function employeeLogin(){const emp=employees.find(e=>e.id===$("employeeSelect").value);const pin=$("employeePin").value.trim();if(!emp)return toast("Veldu starfsmann");if(!await checkPin(emp,pin))return toast("Rangt PIN");loggedEmployee=emp;$("loggedEmployeeName").textContent=emp.name;$("employeeLogin").classList.add("hidden");$("employeePanel").classList.remove("hidden");$("employeePin").value="";const force=emp.must_change_pin||!emp.pin_hash;if(force)showChangePin(true)
;else hideChangePin();renderMyEntries();toast("Innskráning tókst")}
function employeeLogout(){loggedEmployee=null;$("employeePanel").classList.add("hidden");$("clockOutBox").classList.add("hidden");$("employeeLogin").classList.remove("hidden");hideChangePin();renderMyEntries()}
function showChangePin(force=false){$("mustChangePinBox").classList.remove("hidden");$("employeeActions").classList.toggle("hidden",!!force)}
function hideChangePin(){$("mustChangePinBox").classList.add("hidden");$("employeeActions").classList.remove("hidden");["changeOldPin","changeNewPin","changeNewPin2"].forEach(id=>$(id).value="")}
async function changeMyPin(){const emp=loggedEmployee;if(!emp)return;const old=$("changeOldPin").value.trim(),n1=$("changeNewPin").value.trim(),n2=$("changeNewPin2").value.trim();if(!await checkPin(emp,old))return toast("Núverandi PIN er rangt");if(n1.length<4)return toast("Nýtt PIN þarf minnst 4 stafi");if(n1!==n2)return toast("Ný PIN passa ekki saman");const pin_hash=await sha256(n1);const{error}=await db.from("employees").update({pin_hash,pin_code:null,must_change_pin:false}).eq("id",emp.id);if(error){console.error(error);return toast("Villa við PIN breytingu")}emp.pin_hash=pin_hash;emp.pin_code=null;emp.must_change_pin=false;toast("PIN breytt");hideChangePin();await loadEmployees()}
function requireLoggedEmployee(){if(!loggedEmployee){toast("Þú þarft að skrá þig inn með PIN");return null}return loggedEmployee}

async function clockIn(){const emp=requireLoggedEmployee();if(!emp)return;const{data:open}=await db.from("time_entries").select("*").eq("employee_id",emp.id).is("clock_out",null).limit(1);if(open&&open.length)return toast("Þú ert nú þegar mætt/ur");const{error}=await db.from("time_entries").insert({employee_id:emp.id,employee_name:emp.name,clock_in:new Date().toISOString(),note:""});if(error){console.error(error);return toast("Villa við mætingu")}toast("✅ Mæting skráð");await loadEntries();await loadOpenEntries();setTimeout(employeeLogout,900)}
async function showClockOut(){$("clockOutBox").classList.toggle("hidden");await previewPaid()}
async function previewPaid(){const emp=requireLoggedEmployee();if(!emp)return;const{data}=await db.from("time_entries").select("*").eq("employee_id",emp.id).is("clock_out",null).order("clock_in",{ascending:false}).limit(1);if(!data||!data.length){$("paidPreview").textContent="Engin opin mæting fannst.";return}const entry=data[0];const base=Math.max(0,Math.round((new Date()-new Date(entry.clock_in))/60000));const fc=$("firstCoffee").checked,sc=$("secondCoffee").checked,lu=$("lunch").checked;const skipped=skippedBreakMinutes(fc,sc,lu);$("paidPreview").innerHTML=`Rauntími: <b>${minsText(base)}</b><br>Sleppt hlé bætist við: <b>+${minsText(skipped)}</b><br>Greiddur tími í dag: <b>${minsText(base+skipped)}</b>`}
async function clockOut(){const emp=requireLoggedEmployee();if(!emp)return;const{data,error}=await db.from("time_entries").select("*").eq("employee_id",emp.id).is("clock_out",null).order("clock_in",{ascending:false}).limit(1);if(error||!data||!data.length)return toast("Engin opin mæting fannst");const entry=data[0],out=new Date();const base=Math.max(0,Math.round((out-new Date(entry.clock_in))/60000));const fc=$("firstCoffee").checked,sc=$("secondCoffee").checked,lu=$("lunch").checked;const skipped=skippedBreakMinutes(fc,sc,lu);const{error:updateError}=await db.from("time_entries").update({clock_out:out.toISOString(),total_minutes:base,paid_minutes:base+skipped,skipped_break_minutes:skipped,first_coffee:fc,second_coffee:sc,lunch:lu,break_minutes:0}).eq("id",entry.id);if(updateError){console.error(updateError);return toast("Villa við heimferð")}$("firstCoffee").checked=true;$("secondCoffee").checked=true;$("lunch").checked=true;$("clockOutBox").classList.add("hidden");toast("✅ Heimferð skráð");await loadEntries();await loadOpenEntries();setTimeout(employeeLogout,900)}

function adminLogin(){if($("adminPassword").value!==ADMIN_PASSWORD)return toast("Rangt lykilorð");$("adminLogin").classList.add("hidden");$("adminPanel").classList.remove("hidden");toast("Stjórnandi skráður inn")}
function adminLogout(){$("adminPanel").classList.add("hidden");$("adminLogin").classList.remove("hidden")}
function setTab(n,b){document.querySelectorAll(".tabPage").forEach(p=>p.classList.add("hidden"));$(`tab-${n}`).classList.remove("hidden");document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));b.classList.add("active")}
async function addEmployee(){const name=$("newName").value.trim();if(!name)return toast("Vantar nafn");const pin=$("newPin").value.trim()||"1234";const row={name,national_id:$("newNationalId").value.trim(),employee_no:$("newEmployeeNo").value.trim(),pin_code:pin,pin_hash:null,must_change_pin:true,hourly_rate:Number($("newHourlyRate").value||0),active:true};const{error}=await db.from("employees").insert(row);if(error){console.error(error);return toast("Villa við að bæta við starfsmanni")}["newName","newNationalId","newEmployeeNo","newPin","newHourlyRate"].forEach(id=>$(id).value="");toast("Starfsmaður bættur við");await loadEmployees()}
async function editEmployee(id){const emp=employees.find(e=>e.id===id);if(!emp)return;const name=prompt("Nafn:",emp.name);if(!name)return;const national_id=prompt("Kennitala:",emp.national_id||"")??emp.national_id;const employee_no=prompt("Starfsnúmer:",emp.employee_no||"")??emp.employee_no;const hourly_rate=Number(prompt("Tímakaup:",emp.hourly_rate||0)??emp.hourly_rate??0);const{error}=await db.from("employees").update({name,national_id,employee_no,hourly_rate}).eq("id",id);if(error){console.error(error);return toast("Villa við breytingu")}toast("Starfsmanni breytt");await loadEmployees();await loadEntries()}
async function resetEmployeePin(id){const pin=prompt("Nýtt tímabundið PIN:","1234");if(!pin)return;const{error}=await db.from("employees").update({pin_code:pin,pin_hash:null,must_change_pin:true}).eq("id",id);if(error){console.error(error);return toast("Villa við PIN endurstillingu")}toast("PIN endurstillt");await loadEmployees()}
async function hideEmployee(id){if(!confirm("Eyða starfsmanni af lista? Gamlar skráningar geymast."))return;const{error}=await db.from("employees").update({active:false}).eq("id",id);if(error){console.error(error);return toast("Villa við að fela starfsmann")}toast("Starfsmaður falinn");await loadEmployees()}
async function addManualEntry(){const emp=employees.find(e=>e.id===$("manualEmployee").value);if(!emp)return toast("Veldu starfsmann");const date=$("manualDate").value;if(!date)return toast("Veldu dagsetningu");const type=$("manualType").value;const ci=localISO(date,$("manualIn").value),co=localISO(date,$("manualOut").value);let base=Math.max(0,Math.round((new Date(co)-new Date(ci))/60000));const fc=$("manualFirstCoffee").checked,sc=$("manualSecondCoffee").checked,lu=$("manualLunch").checked;let skipped=skippedBreakMinutes(fc,sc,lu),paid=base+skipped;if(type){base=0;skipped=0;paid=0}const{error}=await db.from("time_entries").insert({employee_id:emp.id,employee_name:emp.name,clock_in:ci,clock_out:co,total_minutes:base,paid_minutes:paid,skipped_break_minutes:skipped,first_coffee:fc,second_coffee:sc,lunch:lu,manual:true,absence_type:type||null,note:$("manualNote").value||"Handvirk skráning"});if(error){console.error(error);return toast("Villa við handvirka skráningu")}toast("Handvirk skráning vistuð");await loadEntries();await loadOpenEntries()}
async function deleteEntry(id){if(!confirm("Eyða þessari skráningu?"))return;const{error}=await db.from("time_entries").delete().eq("id",id);if(error){console.error(error);return toast("Villa við eyðingu")}toast("Skráningu eytt");await loadEntries();await loadOpenEntries()}
async function saveSettings(){const rows=[["first_coffee_minutes",$("settingFirstCoffee").value||15],["second_coffee_minutes",$("settingSecondCoffee").value||15],["lunch_minutes",$("settingLunch").value||30],["overtime_after_hours_day",$("settingOvertime").value||8]].map(([key,value])=>({key,value:String(value),updated_at:new Date().toISOString()}));for(const r of rows)await db.from("app_settings").upsert(r);toast("Stillingar vistaðar");await loadSettings();await loadEntries()}
function downloadCSV(){const header=["Kennitala","Starfsnúmer","Starfsmaður","Mætti","Fór","Raun mín","Greiddar mín","Greiddur tími","Sleppt hlé mín","Tímakaup","Áætluð laun","Fyrra kaffi tekið","Seinna kaffi tekið","Matur tekinn","Athugasemd","Fjarvist"];const rows=entries.map(e=>{const emp=employees.find(x=>x.id===e.employee_id||x.name===e.employee_name)||{};const paid=Number(e.paid_minutes??e.total_minutes??0);const wage=Math.round((Number(emp.hourly_rate||0)*paid)/60);return[emp.national_id,emp.employee_no,e.employee_name,fmtDate(e.clock_in),fmtDate(e.clock_out),e.total_minutes,paid,minsText(paid),e.skipped_break_minutes,emp.hourly_rate||0,wage,e.first_coffee?"Já":"Nei",e.second_coffee?"Já":"Nei",e.lunch?"Já":"Nei",e.note,e.absence_type].map(csvEscape).join(";")});const blob=new Blob(["\ufeff"+header.join(";")+"\n"+rows.join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="totu-vinnutimi-pro-v21.csv";a.click()}
function copyPayroll(){const lines=[...document.querySelectorAll("#summary tbody tr")].map(tr=>{const c=[...tr.children].map(td=>td.textContent);return`${c[0]} – greiddur tími ${c[3]} – áætluð laun ${c[6]} (sleppt hlé ${c[4]}, yfirvinna ${c[5]})`});navigator.clipboard.writeText(lines.join("\n"));toast("Launalisti afritaður")}
async function backup(){const[e,t,s]=await Promise.all([db.from("employees").select("*"),db.from("time_entries").select("*"),db.from("app_settings").select("*")]);const blob=new Blob([JSON.stringify({employees:e.data,time_entries:t.data,settings:s.data,exported_at:new Date().toISOString()},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="totu-vinnutimi-backup.json";a.click()}
init();
